// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	JWT_TokenService_GenerateJWt_FullMethodName = "/auth.JWT_TokenService/GenerateJWt"
)

// JWT_TokenServiceClient is the client API for JWT_TokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JWT_TokenServiceClient interface {
	GenerateJWt(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
}

type jWT_TokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJWT_TokenServiceClient(cc grpc.ClientConnInterface) JWT_TokenServiceClient {
	return &jWT_TokenServiceClient{cc}
}

func (c *jWT_TokenServiceClient) GenerateJWt(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, JWT_TokenService_GenerateJWt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JWT_TokenServiceServer is the server API for JWT_TokenService service.
// All implementations must embed UnimplementedJWT_TokenServiceServer
// for forward compatibility
type JWT_TokenServiceServer interface {
	GenerateJWt(context.Context, *GenerateRequest) (*GenerateResponse, error)
	mustEmbedUnimplementedJWT_TokenServiceServer()
}

// UnimplementedJWT_TokenServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJWT_TokenServiceServer struct {
}

func (UnimplementedJWT_TokenServiceServer) GenerateJWt(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateJWt not implemented")
}
func (UnimplementedJWT_TokenServiceServer) mustEmbedUnimplementedJWT_TokenServiceServer() {}

// UnsafeJWT_TokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JWT_TokenServiceServer will
// result in compilation errors.
type UnsafeJWT_TokenServiceServer interface {
	mustEmbedUnimplementedJWT_TokenServiceServer()
}

func RegisterJWT_TokenServiceServer(s grpc.ServiceRegistrar, srv JWT_TokenServiceServer) {
	s.RegisterService(&JWT_TokenService_ServiceDesc, srv)
}

func _JWT_TokenService_GenerateJWt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWT_TokenServiceServer).GenerateJWt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JWT_TokenService_GenerateJWt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWT_TokenServiceServer).GenerateJWt(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JWT_TokenService_ServiceDesc is the grpc.ServiceDesc for JWT_TokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JWT_TokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.JWT_TokenService",
	HandlerType: (*JWT_TokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateJWt",
			Handler:    _JWT_TokenService_GenerateJWt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}
